eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

spring:
  zipkin:
    baseurl: http://zipkin-svc:9411

okta:
  oauth2:
    issuer: https://dev-57633243-admin.okta.com/oauth2/default
    audience: api://default

